config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: (0..5), allow_nil: false }, numericality: { only_integer: true }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurants_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: 'Restaurant crée avec talent et respect.'
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
     if @restaurant.update(restaurants_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurants_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(reviews_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant) , notice: 'well done bro!.'
    else
      render :new
    end
  end

  private

  def reviews_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= simple_form_for(@restaurant) do |f| %>


  <div class="form-inputs">

    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>


  <div class="container">
    <div class="row">
      <div class="col-2 offset-1">
          <p>Name</p>
      </div>
      <div class="col-2">
          <p>Address</p>
      </div>
      <div class="col-2">
          <p>Phone number</p>
      </div>
      <div class="col-2">
          <p>Category</p>
      </div>
      <div class="col-2">
          <p>links</p>
      </div>
    </div>
  </div>


    <% @restaurants.each do |restaurant| %>
      <div class="row">
        <div class="col-2 offset-1">
          <p><%= restaurant.name %></p>
        </div>
        <div class="col-2">
          <p><%= restaurant.address %></p>
        </div>
        <div class="col-2">
          <p><%= restaurant.phone_number %></p>
        </div>
        <div class="col-2">
          <p><%= restaurant.category %></p>
        </div>
        <div class="col-2">
          <tr><%= link_to 'Show', restaurant %></tr>
          <tr><%= link_to 'Edit', edit_restaurant_path(restaurant) %></tr>
          <tr><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></tr>
        </div>
      </div>

    <% end %>


<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <div class="form-inputs">

    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>


<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>phone number: :</strong>
  <%= @restaurant.phone_number%>
</p>

<p>
  <strong>category:</strong>
  <%= @restaurant.category %>
</p>

<h2>The reviews of this resto</h2>
<% @restaurant.reviews.each do |review| %>
  <p><%= review.content %></p>
<% end %>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

<%= link_to 'new review',  new_restaurant_review_path(restaurant_id: @restaurant)%>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <div class="form-inputs">
    <%= f.input :content %>

  </div>
  <%= f.input :rating %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>